name: MasterDeployCI
on:
  push:
    branches:
      - alpha
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
    - uses: nodenv/actions/node-version
      id: nodenv
    - uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nodenv.outputs.node-version }}'
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{ secrets.GH_EMAIL }}
        git config --global user.name ${{ secrets.GH_USERNAME }}
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/mind-broom.git
        npm run deploy
