name: AlphaDeployGHPages
on:
  push:
    branches:
      - alpha
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Detect local Node version
      uses: nodenv/actions/node-version@v2
      id: nodenv
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nodenv.outputs.node-version }}'
    - name: Install Packages
      run: npm ci
    - name: Build for Production
      run: npm run build
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{ secrets.GH_EMAIL }}
        git config --global user.name ${{ secrets.GH_USERNAME }}
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/mind-broom.git
        npm run deploy
